-- Spec_Marksmanship.lua --------------------------------------------------------
-- Marksmanship Hunter (spec 254), patch 12.1. All-inclusive lists covering both
-- Sentinel and Dark Ranger -- untalented abilities (Black Arrow / Wailing Arrow /
-- Moonlight Chakram) are filtered by IsKnown, and buff-gated lines go inert when
-- the buff never appears. Spell IDs are best-guess; verify with /prio spells.
--------------------------------------------------------------------------------

local ADDON, PRIO = ...
PRIO.specs = PRIO.specs or {}

local FOCUS = (Enum and Enum.PowerType and Enum.PowerType.Focus) or 2

-- Readable buff IDs (verify with /prio tracked).
local ID_PRECISE = 260242   -- Precise Shots
local ID_TRICK   = 257622   -- Trick Shots

local function AND(...) return { op = "and", clauses = { ... } } end
local function OR(...)  return { op = "or",  clauses = { ... } } end
local function buffUp(id)   return { type = "buffActive",  spell = id } end
local function buffDown(id) return { type = "buffMissing", spell = id } end

local spec = {
    key      = "HUNTER_MARKSMANSHIP",
    label    = "Marksmanship",
    specID   = 254,
    resource = FOCUS,
    resourceLabel = "Focus",
    cleaveAt = 2,   -- AoE (Multi-Shot / Trick Shots) starts at 2 targets
    aoeAt    = 3,

    spells = {
        AimedShot       = 19434,
        RapidFire       = 257044,
        ArcaneShot      = 185358,
        SteadyShot      = 56641,
        MultiShot       = 257620,
        ExplosiveShot   = 212431,
        Volley          = 260243,
        Trueshot        = 288613,
        KillShot        = 53351,
        BlackArrow      = 466930,   -- Dark Ranger
        WailingArrow    = 392060,   -- Dark Ranger
        MoonlightChakram = 471847,  -- Sentinel
        HuntersMark     = 257284,
    },

    openerReady = { "Trueshot" },
    opener = { "HuntersMark", "AimedShot", "ExplosiveShot", "ExplosiveShot",
               "Volley", "Trueshot", "RapidFire", "AimedShot", "ArcaneShot", "AimedShot" },

    precombat = {
        { spell = "HuntersMark", aura = 257284 },
    },

    pickable = {
        "AimedShot", "RapidFire", "ArcaneShot", "MultiShot", "ExplosiveShot",
        "Volley", "Trueshot", "KillShot", "BlackArrow", "WailingArrow",
        "MoonlightChakram", "SteadyShot", "HuntersMark",
    },

    -- Aimed Shot runs on charges.
    chargeTrack = {
        AimedShot = { max = 2, recharge = 12 },
    },

    fillers = { [56641] = true },   -- Steady Shot

    flash = {
        ArcaneShot = { type = "buffActive", spell = ID_PRECISE },
        KillShot   = { type = "buffActive", spell = ID_PRECISE },
        BlackArrow = { type = "buffActive", spell = ID_PRECISE },
    },

    -- Precise Shots: generated by Aimed Shot / Rapid Fire, spent by Arcane / Kill /
    -- Black Arrow / Multi-Shot. Trick Shots: from Multi-Shot, spent by Aimed / Rapid.
    spellEffects = {
        AimedShot   = { grant = { ID_PRECISE }, consume = { ID_TRICK } },
        RapidFire   = { grant = { ID_PRECISE }, consume = { ID_TRICK } },
        MultiShot   = { grant = { ID_TRICK }, consume = { ID_PRECISE } },
        ArcaneShot  = { consume = { ID_PRECISE } },
        KillShot    = { consume = { ID_PRECISE } },
        BlackArrow  = { consume = { ID_PRECISE } },
    },

    maelstromMax = 100,   -- Focus cap (generic "resource" fields)
    maelstromGen = {
        SteadyShot = 10,
        RapidFire  = 0,
    },

    OnCast = function(P, key, now) end,

    priority = {
        -- Single target (Sentinel + Dark Ranger merged).
        st = {
            { spell = "BlackArrow",  cond = buffUp(ID_PRECISE) },   -- DR: spend Precise Shots
            { spell = "ExplosiveShot" },                            -- on CD (2 casts via Unstable Trigger)
            { spell = "Volley" },
            { spell = "Trueshot" },
            { spell = "KillShot",   cond = buffUp(ID_PRECISE) },    -- spend Precise Shots
            { spell = "ArcaneShot", cond = buffUp(ID_PRECISE) },    -- spend Precise Shots
            { spell = "RapidFire" },
            { spell = "WailingArrow" },                             -- DR: on CD
            { spell = "AimedShot" },                                -- on CD (charges)
            { spell = "MoonlightChakram" },                         -- Sentinel
            { spell = "BlackArrow" },                               -- DR: filler
            { spell = "SteadyShot" },                               -- filler
        },

        -- Cleave / AoE (Trick Shots). Multi-Shot replaces Arcane as the Precise
        -- Shots spender and keeps Trick Shots up for Aimed / Rapid Fire.
        cleave = {
            { spell = "ExplosiveShot" },
            { spell = "Volley" },
            { spell = "BlackArrow", cond = buffUp(ID_PRECISE) },
            { spell = "Trueshot" },
            { spell = "MultiShot",  cond = buffDown(ID_TRICK) },    -- put Trick Shots up
            { spell = "MultiShot",  cond = buffUp(ID_PRECISE) },    -- spend Precise Shots
            { spell = "RapidFire",  cond = buffUp(ID_TRICK) },
            { spell = "AimedShot",  cond = buffUp(ID_TRICK) },
            { spell = "WailingArrow" },
            { spell = "MoonlightChakram" },
            { spell = "SteadyShot" },
        },
    },
}
spec.priority.aoe = spec.priority.cleave   -- same list for 3+

PRIO.specs[spec.specID] = spec
